openapi: 3.0.0
info:
  title: VU RCON API
  description: API Routes for Venice Unleashed RCON Tool
  version: 0.1.9
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt
tags:
  - name: auth
    description: routes which handle authentication stuff
  - name: instance
    description: instance related routes
paths:
  /api/auth/login:
    $ref: "paths/auth/login.yaml"
  /api/instances:
    $ref: "paths/instances/index.yaml"
  /api/instances/{id}:
    $ref: "paths/instances/single/index.yaml"
  /api/instances/{id}/start:
    $ref: "paths/instances/single/start.yaml"
  /api/instances/{id}/stop:
    $ref: "paths/instances/single/stop.yaml"