# enables some development features
development: true
database:
  #see https://github.com/typeorm/typeorm/blob/master/docs/connection-options.md for details
  use: "sqlite"
  sqlite:
    database: "./rcon.db"
  mariadb:
    host: "127.0.0.1"
    port: 3306
    username: ""
    password: ""
    database: "battlefield"
webserver:
  #port which the webserver listens to
  listenport: 8000
  jwt:
    #maxmimum token age in days
    maxAge: 7
    #time in days after a new token gets issued
    sendRefresh: 5
  #set cors when requests comes from one of those domains
  cors:
    - "https://alliance-apps.github.io"
instance:
  #default time in ms of how many updates get sent to the rcon server
  syncInterval: 5000
  plugins:
    #location of the directory to read plugins from
    baseDir: "./plugins"
    #time in minutes until the remote repo store gets reloaded
    #from the external url
    reloadInterval: 60
    repos:
      - name: "main"
        repository: "https://github.com/Multivit4min/vu-plugin-repo/"