# enables some development features
development: true
database:
  #see https://github.com/typeorm/typeorm/blob/master/docs/connection-options.md for details
  use: "sqlite"
  sqlite:
    database: "./rcon.db"
  mariadb:
    host: "127.0.0.1"
    port: 3306
    username: ""
    password: ""
    database: "battlefield"
webserver:
  #port which the webserver listens to
  listenport: 8000
  jwt:
    #maxmimum token age in days
    maxAge: 7
    #time in days after a new token gets issued
    sendRefresh: 5
  #enable webinterface access from rcon.cloud?
  remote_webinterface: true
  #cors are only being set when development has been set to true
  cors:
    Access-Control-Allow-Credentials: "true"
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Methods: "*"
    Access-Control-Max-Age: 7200
    Access-Control-Allow-Headers: 
      - Authorization
      - Content-Type
instance:
  #default time in ms of how many updates get sent to the rcon client
  syncInterval: 1000
  plugins:
    baseDir: "./plugins"
