development: false
database:
  use: "sqlite"
  sqlite:
    database: "./db.sql"
  mariadb:
    host: "127.0.0.1"
    port: 3306
    username: ""
    password: ""
    database: "battlefield"
webserver:
  listenport: 8000