# enables some development features
# if set to true then you can access via route /swagger the api docs
development: false
database:
  #see https://github.com/typeorm/typeorm/blob/master/docs/connection-options.md for details
  use: "sqlite"
  sqlite:
    database: "./rcon.db"
  mariadb:
    host: "127.0.0.1"
    port: 3306
    username: ""
    password: ""
    database: "battlefield"
webserver:
  #port which the webserver listens to
  listenport: 8000
  #cors are only being set when development has been set to true
  cors:
    Access-Control-Allow-Credentials: "true"
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Headers: 
      - Authorization
      - Content-Type
instance:
  #default time in ms of how many updates get sent to the rcon client
  syncInterval: 1000